name: Date Structures in Dart
version: 0.0.1
#homepage: https://www.example.com
author: artem_galas <artem.galas@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.2.0
